# Generated by Django 3.0.8 on 2020-08-11 22:34

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('savvyapp', '0002_auto_20200810_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='neighborhood',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=tinymce.models.HTMLField(verbose_name='Location/Neighborhood'),
        ),
    ]
