# Generated by Django 3.0.8 on 2020-07-31 20:27

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('savvyapp', '0002_auto_20200731_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=tinymce.models.HTMLField(default='a bio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
