# Generated by Django 3.0.8 on 2020-07-31 21:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('savvyapp', '0003_auto_20200731_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=tinymce.models.HTMLField(default='Nairobi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='neighborhood',
            field=tinymce.models.HTMLField(default='Nairobi'),
            preserve_default=False,
        ),
    ]
